### ISSUE TITLE
While running the d3net music seperation jupyter notebook in collab "AttributeError: module 'pynvml.nvml' has no attribute 'nvml_lib'" error is coming

### ISSUE THREAD

**Issue by sunilbage** [sony/ai-research-code#18]
2021-06-07 12:26:53,837 [nnabla][INFO]: Initializing CPU extension...
Traceback (most recent call last):
  File "separate.py", line 96, in <module>
    ch_flip_average=True
  File "separate.py", line 27, in run_separation
    ctx = get_extension_context(args.context)
  File "/usr/local/lib/python3.7/dist-packages/nnabla/ext_utils.py", line 97, in get_extension_context
    mod = import_extension_module(ext_name)
  File "/usr/local/lib/python3.7/dist-packages/nnabla/ext_utils.py", line 46, in import_extension_module
    return importlib.import_module('.' + ext_name, 'nnabla_ext')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/nnabla_ext/cudnn/__init__.py", line 18, in <module>
    import nnabla_ext.cuda
  File "/usr/local/lib/python3.7/dist-packages/nnabla_ext/cuda/__init__.py", line 114, in <module>
    check_gpu_compatibility()
  File "/usr/local/lib/python3.7/dist-packages/nnabla_ext/cuda/__init__.py", line 71, in check_gpu_compatibility
    from nnabla.utils.nvml import pynvml
  File "/usr/local/lib/python3.7/dist-packages/nnabla/utils/nvml.py", line 39, in <module>
    load_nvml_for_win()
  File "/usr/local/lib/python3.7/dist-packages/nnabla/utils/nvml.py", line 26, in load_nvml_for_win
    if not (nvml.nvml_lib == None and sys.platform[:3] == "win"):
AttributeError: module 'pynvml.nvml' has no attribute 'nvml_lib'

**Comment by TakuyaNarihira** [comment]
Thanks for reporting the issue. It's been fixed in https://github.com/sony/nnabla/issues/892 (see also the workaround), and the fixed binary will be available in the next release of nnabla.

**Comment by TakuyaNarihira** [comment]
Closing this since this has been fixed in nnabla v1.20.0. Please reopen this issue if the problem still exists.
