### ISSUE TITLE
Potential bug in xumx

### ISSUE THREAD

**Issue by sevagh** [sony/ai-research-code#26]
I'm trying to run xumx (through https://github.com/JeffreyCA/spleeterweb-xumx, but it seems to be the same code).

In this line: https://github.com/sony/ai-research-code/blob/4c02f0a949e479cb15da03669dcf2ae4ff114215/x-umx/test.py#L79 

The function documentation says audio should be in the shape:
```
    audio: np.ndarray [shape=(nb_samples, nb_channels, nb_timesteps)]
        mixture audio
```

However, the ndarray is converted to a nnabla object with a transpose operator and a new dimension added:
```
    audio_nn = nn.Variable.from_numpy_array(audio.T[None, ...])
```
So when I pass audio like so:
```
x.shape: (1, 2, 9265664)
```
the audio_nn line results in this:
```
audio_nn: (1, 9265664, 2, 1)
```
Later on this fails in the STFT step from the `__call__` function of the model:
https://github.com/sony/ai-research-code/blob/4c02f0a949e479cb15da03669dcf2ae4ff114215/x-umx/model.py#L29

It's better to have:
```
    audio_nn = nn.Variable.from_numpy_array(audio)
```

**Comment by sevagh** [comment]
Also, my predictions are all 0 when I use the pretrained model I downloaded from https://nnabla.org/pretrained-models/ai-research-code/x-umx/x-umx.h5

```
+ export MUSDB_PATH=/home/sevagh/TRAINING-MUSIC/MUSDB18-HQ/
2021-07-30 00:49:18,277 [nnabla][INFO]: Initializing CPU extension...
evaluating track AM Contra - Heart Peripheral with model xumx
{'bass': array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]]), 'drums': array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]]), 'vocals': array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]]), 'other': array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])}
bss evaluation
```
xumx code running an evaluation on MUSDB18-HQ:
```
from xumx.test import separate

estimates = separate(np.expand_dims(track.audio.T, axis=0), model_path="/path/to/x-umx.h5")
print(estimates)
```

For comparison, the same code but using regular umx seems to work fine, indicating the audio I'm passing is OK:
```
evaluating track AM Contra - Heart Peripheral with model umx
{'vocals': array([[-5.4652509e-09,  1.1636184e-08],
       [-2.5145270e-09,  1.0023978e-08],
       [-9.9477342e-09,  2.0257951e-09],
       ...,
       [-2.2504205e-06, -2.2573504e-06],
       [-2.5963650e-06, -2.6467073e-06],
       [-2.7232165e-06, -3.5706269e-06]], dtype=float32), 'drums': array([[-3.0273603e-07, -4.4931366e-07],
```
I'm wondering how I can debug the inference failure of x-umx.

**Comment by sevagh** [comment]
Confirmed the Sony research code from this repository is behaving the same way.

**Comment by TE-BasavarajMurali** [comment]
Hi @sevagh,
Thanks for reporting.

We have just verified the code and uploaded pre-trained model, it works without any error and we got the desired outputs.
Only the function documentation regarding audio shape is not correct in the below line:
https://github.com/sony/ai-research-code/blob/4c02f0a949e479cb15da03669dcf2ae4ff114215/x-umx/test.py#L56

Correct shape should be :
`audio: np.ndarray [shape=(nb_timesteps, nb_channels)]`

We'll soon update it.

**Comment by sevagh** [comment]
OK. I discovered the error is on my side. The `separate` function does not do the setup of NNabla. That part is in the `test()` function.

I needed to add code like this, to call X-UMX pretrained from a different Python script:
```
def load_xumx_model(
        model_path='models/x-umx.h5',
        context='cpu'
):
    ctx = get_extension_context(context)
    nn.set_default_context(ctx)

    # Enable the NNabla Dynamic excecution
    nn.set_auto_forward(True)

    max_bin = bandwidth_to_max_bin(sample_rate=44100, n_fft=4096, bandwidth=16000)
    unmix_target = OpenUnmix_CrossNet(max_bin=max_bin)
    unmix_target.is_predict = True
    nn.load_parameters(model_path)

    return unmix_target
```

Right now my bigger issue is with segfaulting. Even with a 10 second chunk duration, I get segfaults:
```
2021-07-30 07:31:29,051 [nnabla][INFO]: Initializing CPU extension...
  0%|                                                                                                   | 0/50 [00:00<?, ?it/s]evaluating track AM Contra - Heart Peripheral with model xumx
CHUNKING FULL AUDIO INTO 441000
                                                                                                                              ./04-umx-models.sh: line 13: 54350 Segmentation fault      (core dumped) $pybin "${scriptdir}/trained_models.py" --eval_dir="${expdir}/"
```
It's a bit unusual because I have 64GB of memory so I don't know which part of X-UMX the segfault possibly comes from.

**Comment by TE-BasavarajMurali** [comment]
Looking at the logs shared in the above comment, it is cunning on `CPU`.
So, can you once try running it on `GPU`?

**Comment by sevagh** [comment]
I think the slow CPU inference is possibly expected: https://github.com/sony/ai-research-code/issues/2
Chunk size of 1 second "works" (but takes forever. After 15 minutes no separation on the first chunk)

Using the 'cudnn' backend, after installing 'nnabla-ext-cuda110':
```
2021-07-30 07:50:48,078 [nnabla][INFO]: Initializing CPU extension...
2021-07-30 07:50:48,510 [nnabla][INFO]: Initializing CUDA extension...
2021-07-30 07:50:48,535 [nnabla][INFO]: Initializing cuDNN extension...
  0%|                                                                                                   | 0/50 [00:00<?, ?it/s]evaluating track AM Contra - Heart Peripheral with model xumx
CHUNKING FULL AUDIO INTO 44100
  0%|                                                                                                  | 0/211 [00:02<?, ?it/s]
  0%|                                                                                                   | 0/50 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "./mss-oracle-experiments/oracle_eval/trained_models.py", line 122, in <module>
    est, _ = pretrained_model(
  File "./mss-oracle-experiments/oracle_eval/trained_models.py", line 60, in pretrained_model
    estimates = xumx_separate_sony(
  File "/home/sevagh/repos/ma_thesis/mss_evaluation/vendor/sony-x-xumx/xumx_sony/test.py", line 92, in separate
    mix_spec, msk, _ = unmix_target(audio_nn, test=True)
  File "/home/sevagh/repos/ma_thesis/mss_evaluation/vendor/sony-x-xumx/xumx_sony/model.py", line 184, in __call__
    x = Spectrogram(fft_real, fft_imag, power=self.power,
  File "/home/sevagh/repos/ma_thesis/mss_evaluation/vendor/sony-x-xumx/xumx_sony/model.py", line 61, in Spectrogram
    return F.transpose(spec, ((3, 0, 1, 2)))
  File "<transpose>", line 3, in transpose
  File "/home/sevagh/venvs/thesis/lib64/python3.8/site-packages/nnabla/function_bases.py", line 3875, in transpose
    return F.Transpose(ctx, axes)(x, n_outputs=n_outputs, auto_forward=get_auto_forward(), outputs=outputs)
  File "function.pyx", line 317, in nnabla.function.Function.__call__
  File "function.pyx", line 295, in nnabla.function.Function._cg_call
RuntimeError: target_specific error in forward_impl
/home/gitlab-runner/builds/-phDBBa6/3/nnabla/builders/all/nnabla-ext-cuda/src/nbla/cuda/function/./generic/transpose.cu:177
(cudaGetLastError()) failed with "invalid configuration argument" (cudaErrorInvalidConfiguration).
```

My GPU is the RTX 3080 Ti. My CUDA version is 11.4 - could it be a CUDA compatibility issue?

**Comment by sevagh** [comment]
OK - it's not as bad as I thought. When re-adding the old transpose + batch_size code:
```
audio_nn = nn.Variable.from_numpy_array(cur_chunk.T[None, ...])
```
I first accidentally did:
```
audio_nn = nn.Variable.from_numpy_array(cur_chunk[None, ...].T)
```
Again mixing up channels and samples, creating huge memory allocations.

**Comment by TE-BasavarajMurali** [comment]
I think it is due to CUDA compatibility issue.

Currently NNabla doesn't support `CUDA-11.4`.
So, can you downgrade the CUDA to `CUDA-11.0` and try once?

**Comment by sevagh** [comment]
Thanks for all the help @TE-BasavarajMurali. CPU inference is working OK.

I don't want to break my CUDA installation by changing toolit (which works for other deep learning frameworks and projects) so I will stick with the CPU for now.

I will close this issue after I can see 1 full track succeed in the estimation and BSS score:
```
2021-07-30 08:12:49,493 [nnabla][INFO]: Initializing CPU extension...
  0%|                                                                                                   | 0/50 [00:00<?, ?it/s]evaluating track AM Contra - Heart Peripheral with model xumx
CHUNKING FULL AUDIO INTO 2646000

 25%|██████████████████████▊                                                                    | 1/4 [02:57<08:51, 177.29s/it]
```

**Comment by sevagh** [comment]
Yep it's working now. Thanks!
```
evaluating track AM Contra - Heart Peripheral with model xumx
100%|███████████████████████████████████████████████████████████████████████████████████████████| 4/4 [10:50<00:00, 162.71s/it]
{'bass': array([[-6.91364488e-06, -4.05640102e-06],█████████████████████████████████████████████| 4/4 [10:50<00:00, 150.57s/it]
       [-6.94204365e-06, -4.07908234e-06],
       [-6.92173995e-06, -4.06321857e-06],
       ...,
       [-1.37219851e-06, -1.30698824e-06],
       [-1.35217950e-06, -1.29504987e-06],
       [-1.39290625e-06, -1.32983888e-06]]), 'drums': array([[ 2.67916351e-07, -4.32465708e-06],
       [ 1.38463017e-06, -4.26450657e-06],
       [ 1.80965058e-06, -1.80896385e-06],
       ...,
       [-1.37591214e-06,  5.00885293e-07],
       [-1.44276491e-06,  1.57423027e-06],
       [-6.57889451e-06, -1.81180482e-06]]), 'vocals': array([[ 2.82000375e-08, -5.33726027e-07],
       [ 1.34451104e-07, -6.67941546e-07],
       [ 4.92464947e-07, -2.65114632e-07],
       ...,
       [ 2.84781878e-08,  5.30249874e-07],
       [-2.96755105e-07,  5.81909853e-07],
       [-6.96862016e-07,  8.41686089e-08]]), 'other': array([[ 3.53654797e-06, -4.80433069e-06],
       [ 3.27676579e-06, -4.60811802e-06],
       [ 2.90315858e-06, -4.04611205e-06],
       ...,
       [-4.11560425e-06, -2.73226030e-06],
       [-4.51717049e-06, -2.89301450e-06],
       [-4.67040757e-06, -3.28004446e-06]])}
bss evaluation
...
```
