### ISSUE TITLE
【NVC-net】Failed `it != items_.end()`: Any of [cudnn:float, cuda:float, cpu:float] could not be found in []

### ISSUE THREAD

**Issue by Charlottecuc** [sony/ai-research-code#40]
Hi. I tried to train NVC-net, but the following error occurs:
```
2021-11-26 03:23:06,638 [nnabla][INFO]: Initializing CPU extension...
2021-11-26 03:23:06,997 [nnabla][INFO]: Initializing CUDA extension...
2021-11-26 03:23:09,117 [nnabla][INFO]: Initializing cuDNN extension...
value error in query
/home/gitlab-runner/builds/zxvvzZDJ/1/nnabla/builders/all/nnabla/include/nbla/function_registry.hpp:69
Failed  it != items_.end() : Any of [cudnn:float, cuda:float, cpu:float] could not be found in []

No communicator found. Running with a single process. If you run this with MPI processes, all processes will perform totally same.
2021-11-26 03:23:09,406 [nnabla][INFO]: Training data with 103 speakers.
2021-11-26 03:23:09,407 [nnabla][INFO]: DataSource with shuffle(True)
2021-11-26 03:23:09,464 [nnabla][INFO]: Using DataIterator
Running epoch=1 lr=0.00010
Failed to allocate. Freeing memory cache and retrying.
Failed to allocate. Freeing memory cache and retrying.
Failed to allocate again.
Error during forward propagation:
```

Environment: Tesla T4, Cuda 10.2, Cudnn 8.1, Ubuntu 18.04.4 LTS.

I installed nnabla with `pip install nnabla-ext-cuda102`.
Besides, if I want to train the model with only one GPU, is `python3 main.py` the right command?

**Comment by Charlottecuc** [comment]
```
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    run(args)
  File "main.py", line 70, in run
    Trainer(gen, gen_optim, dis, dis_optim, dataloader, rng, hp).run()
  File "/NVC-net/vctk/train.py", line 156, in run
    self.train_on_batch(i)
  File "/NVC-net/vctk/train.py", line 195, in train_on_batch
    p['g_loss'].forward()
  File "_variable.pyx", line 581, in nnabla._variable.Variable.forward
RuntimeError: memory error in alloc
/home/gitlab-runner/builds/zxvvzZDJ/1/nnabla/builders/all/nnabla/src/nbla/memory/memory.cpp:39
Failed this->alloc_impl(): N4nbla10CudaMemoryE allocation failed.
```

**Comment by TE-BacNguyenCong** [comment]
As the message indicated, you have run out of memory on GPUs. Reducing the [batch size](https://github.com/sony/ai-research-code/blob/0b643e78fc9d8761d0f066eed19488b2ed339a24/nvcnet/hparams.py#L28) might help.

And for a single GPU,  `python3 main.py` should be ok.
